version: 2
jobs:
    build:
        docker:
            - image: circleci/node:6-stretch
              environment:
                  NODE_ENV: staging
            - image: circleci/postgres:9.6.9-alpine-postgis-ram
              environment:
                  POSTGRES_USER: testuser
                  POSTGRES_DB: matchMyRouteTest
        steps:
            - checkout
            - run: echo "hello world"
            - run: sudo apt install postgresql-client-9.6
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install-npm-wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: test
                command: npm test

    deploy:
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - run: curl -sL https://deb.nodesource.com/setup_6.x | bash -
            - run: apt install -y nodejs
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install-npm-wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            # - run: sudo /opt/google-cloud-sdk/bin/gcloud components update -q
            # - run: sudo chown ubuntu.ubuntu -R /home/ubuntu/.config/gcloud
            - run: gcloud auth activate-service-account --key-file conf/key-file.json
            - run: gcloud config set project matchmyroute-backend
            - run: npm run deploy
            - run: URL=https://matchmyroute-backend.appspot.com npm run e2etest

workflows:
    version: 2
    build-and-deploy:
        jobs:
          # - build
          - deploy
              # requires:
              #   - build
