version: 2
jobs:
    build:
        docker:
            - image: circleci/node:6-stretch
            - image: circleci/postgres:9.6.9-alpine-postgis-ram
              environment:
                  POSTGRES_USER: testuser
                  POSTGRES_DB: matchMyRouteTest
        steps:
            - checkout
            - run: echo "hello world"
            - run: sudo apt install postgresql-client-9.6
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install-npm-wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: test
                command: npm test
