runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1 # default is 2
  max_num_instances: 1
#  cool_down_period_sec: 120 # default value
#  cpu_utilization:
#    target_utilization: 0.5

env_variables:
  NODE_ENV: "development"
  PROCESS_TYPE: "web"
  WITH_SERVICES: true
  NODE_PATH: .
  PGPASSWORD: "aUZw[:Gw38H&>Jf2hUwd"
  DB_CONNECTION_PATH: "/cloudsql/matchmyroute-backend:us-east1:matchmyroute-database"
  DOCURL: "https://matchmyroute-backend.appspot.com"
  STATIC_DIR: "static"

#resources:
#  cpu: .1
#  memory_gb: .18
#  disk_size_gb: 10

beta_settings:
  # Connection to the database
  cloud_sql_instances: matchmyroute-backend:us-east1:matchmyroute-database
