runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1 # default is 2
  max_num_instances: 1
#  cool_down_period_sec: 120 # default value
#  cpu_utilization:
#    target_utilization: 0.5

env_variables:
  NODE_ENV: "development"
  PROCESS_TYPE: "web"
  WITH_SERVICES: true
  NODE_PATH: .
  # GCLOUD_PROJECT: matchmyroute-backend
#  CLOUDSDK_CORE_PROJECT: timepix-dev
#  DATASTORE_PROJECT_ID: timepix-dev
#  # Testing App Engine Memcache service (currently in alpha)
#  USE_GAE_MEMCACHE: 1
#  # otherweise we can use another service such as redislab
#  # MEMCACHE_URL: pub-memcache-16904.us-east-1-2.1.ec2.garantiadata.com:16904
#  # If you are using a Memcached server with SASL authentiation enabled,
#  # fill in these values with your username and password.
#  #  MEMCACHE_USERNAME: sebastian.ovide@geovation.uk
#  #  MEMCACHE_PASSWORD: 4hflupdoTV1R

#resources:
#  cpu: .1
#  memory_gb: .18
#  disk_size_gb: 10

#beta_settings:
#  # Enable Google Cloud Endpoints API management.
#  use_endpoints_api_management: true
#  # Specify the Swagger API specification.
#  endpoints_swagger_spec_file: swagger.yaml:
#  machine_type: f1-micro
