// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!!!!!!

import { APIEndpointCollection } from "./api-endpoint-collection";
import { registerServices } from "./helper";

// IMPORT MICROSERVICES
import { images } from "./images";

const apiEndpointCollection: APIEndpointCollection = new APIEndpointCollection();

// ADD MICROSERVICES TO EXPORT
apiEndpointCollection.addApiEndpointCollection(images);

export const servicesHelper = registerServices(apiEndpointCollection);
